# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# added some code to show it doesn't do anything

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: npm install --production && PORT=5001 npm start
  displayName: 'npm install and start'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
